//! Sync diagrams to IDE context files for AI-assisted development.

use std::path::Path;
use tracing::info;

use crate::error::{self, Result};
use crate::planner;

/// Supported IDE targets.
pub enum EditorTarget {
    Cursor,
    Windsurf,
    Generic,
}

impl EditorTarget {
    /// Parse a target name (case-insensitive).
    pub fn parse(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "cursor" => EditorTarget::Cursor,
            "windsurf" => EditorTarget::Windsurf,
            _ => EditorTarget::Generic,
        }
    }

    /// The filename this target writes to in the repo root.
    pub fn filename(&self) -> &str {
        match self {
            EditorTarget::Cursor => ".cursorrules",
            EditorTarget::Windsurf => ".windsurf-context",
            EditorTarget::Generic => ".ai-context.md",
        }
    }
}

/// Generate IDE context content with architecture diagrams embedded.
pub fn generate_context(
    root: &Path,
    target: &EditorTarget,
    scopes: Option<&[String]>,
) -> Result<String> {
    let manifest = planner::load_manifest(root)?;
    let files = planner::load_file_index(root)?;

    let mut sections = Vec::new();

    // Header — format varies by target
    match target {
        EditorTarget::Cursor => {
            sections
                .push("# Architecture Context (auto-generated by llmermaid)".to_string());
            sections.push(
                "# Do not edit manually -- run `llmermaid sync-editor` to regenerate.\n"
                    .to_string(),
            );
        }
        _ => {
            sections.push(
                "<!-- Architecture context auto-generated by llmermaid -->".to_string(),
            );
            sections.push(
                "<!-- Run `llmermaid sync-editor` to regenerate -->\n".to_string(),
            );
        }
    }

    // Resolve which scopes to include
    let selected_scopes: Vec<String> = match scopes {
        Some(s) => s.to_vec(),
        None => {
            let mut all: Vec<String> = manifest.iter().map(|m| m.scope.clone()).collect();
            all.sort();
            all.dedup();
            all
        }
    };

    sections.push("## System Architecture\n".to_string());

    for entry in &manifest {
        if selected_scopes.contains(&entry.scope) || entry.scope == "root" {
            let content = read_diagram_content(root, &entry.source);
            if !content.is_empty() {
                sections.push(format!(
                    "<{scope}_diagram>\n```mermaid\n{content}\n```\n</{scope}_diagram>\n",
                    scope = entry.scope,
                ));
            }
        }
    }

    // Domain summary
    sections.push("## Domains\n".to_string());
    for scope in &selected_scopes {
        let file_count = files.iter().filter(|f| &f.domain == scope).count();
        if file_count > 0 {
            sections.push(format!("- **{scope}**: {file_count} files"));
        }
    }

    Ok(sections.join("\n"))
}

/// Read diagram content from the extracted diagrams directory.
fn read_diagram_content(root: &Path, source: &str) -> String {
    let safe_name = format!(
        "{}.mmd",
        source
            .replace('/', "__")
            .replace('#', "_")
            .trim_end_matches(".mmd")
    );
    let extracted = crate::config::output_dir(root)
        .join("diagrams")
        .join("extracted")
        .join(&safe_name);

    std::fs::read_to_string(extracted).unwrap_or_default()
}

/// Write the generated context to the target file in the repo root.
pub fn sync(root: &Path, target: &EditorTarget, scopes: Option<&[String]>) -> Result<()> {
    let content = generate_context(root, target, scopes)?;
    let output = root.join(target.filename());

    std::fs::write(&output, &content).map_err(|e| error::io_err(&output, e))?;

    info!(
        path = %output.display(),
        bytes = content.len(),
        "Synced editor context"
    );

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn editor_target_parse_cursor() {
        assert_eq!(EditorTarget::parse("cursor").filename(), ".cursorrules");
        assert_eq!(EditorTarget::parse("Cursor").filename(), ".cursorrules");
    }

    #[test]
    fn editor_target_parse_windsurf() {
        assert_eq!(
            EditorTarget::parse("windsurf").filename(),
            ".windsurf-context"
        );
    }

    #[test]
    fn editor_target_parse_generic_fallback() {
        assert_eq!(
            EditorTarget::parse("vscode").filename(),
            ".ai-context.md"
        );
        assert_eq!(
            EditorTarget::parse("unknown").filename(),
            ".ai-context.md"
        );
    }

    #[test]
    fn generate_context_requires_index() {
        let dir = tempfile::tempdir().unwrap();
        let result = generate_context(dir.path(), &EditorTarget::Cursor, None);
        // Should fail because no manifest.json exists
        assert!(result.is_err());
    }

    #[test]
    fn generate_context_with_manifest() {
        let dir = tempfile::tempdir().unwrap();
        let claude_dir = dir.path().join(".claude");
        std::fs::create_dir_all(&claude_dir).unwrap();

        let manifest = serde_json::json!({
            "generated_at": "2026-01-01T00:00:00Z",
            "diagrams": [
                {
                    "id": "root-arch",
                    "source": "docs/arch.mmd",
                    "domain": "root",
                    "type": "flowchart",
                    "tokens_est": 50
                }
            ]
        });
        std::fs::write(
            claude_dir.join("manifest.json"),
            serde_json::to_string_pretty(&manifest).unwrap(),
        )
        .unwrap();

        let index = serde_json::json!({
            "generated_at": "2026-01-01T00:00:00Z",
            "root": "test",
            "claude_md_paths": [],
            "files": [
                {
                    "path": "src/main.rs",
                    "file_type": "module",
                    "domain": "root",
                    "subdomain": "core",
                    "claude_md": ""
                }
            ]
        });
        std::fs::write(
            claude_dir.join("file-index.json"),
            serde_json::to_string_pretty(&index).unwrap(),
        )
        .unwrap();

        let content =
            generate_context(dir.path(), &EditorTarget::Cursor, None).unwrap();
        assert!(content.contains("Architecture Context"));
        assert!(content.contains("Domains"));
    }

    #[test]
    fn sync_writes_file() {
        let dir = tempfile::tempdir().unwrap();
        let claude_dir = dir.path().join(".claude");
        std::fs::create_dir_all(&claude_dir).unwrap();

        let manifest = serde_json::json!({
            "generated_at": "2026-01-01T00:00:00Z",
            "diagrams": []
        });
        std::fs::write(
            claude_dir.join("manifest.json"),
            serde_json::to_string_pretty(&manifest).unwrap(),
        )
        .unwrap();

        let index = serde_json::json!({
            "generated_at": "2026-01-01T00:00:00Z",
            "root": "test",
            "claude_md_paths": [],
            "files": []
        });
        std::fs::write(
            claude_dir.join("file-index.json"),
            serde_json::to_string_pretty(&index).unwrap(),
        )
        .unwrap();

        let target = EditorTarget::Generic;
        sync(dir.path(), &target, None).unwrap();

        let output = dir.path().join(".ai-context.md");
        assert!(output.exists());
    }
}
